type Dog {
    id: ID!
    name: String
    age: Int
    breed: DogBreed
    color: String
    favouriteFood: [Food]
    owner: Owner
}

type Owner {
    id: ID!
    firstName: String
    lastName: String
    age: Int
    dogs: [Dog!]!
}

type DogPage {
    content: [Dog!]!
    totalElements: Int!
    totalPages: Int!
    pageNumber: Int!
    pageSize: Int!
}

type OwnerPage {
    content: [Owner!]!
    totalElements: Int!
    totalPages: Int!
    pageNumber: Int!
    pageSize: Int!
}

input DogInput {
    name: String!
    age: Int!
    breed: DogBreed!
    color: String!
    favouriteFood: [Food!]!
    ownerId: ID
}

input OwnerInput {
    firstName: String!
    lastName: String!
    age: Int!
}

enum DogBreed {
    HUSKY
    AMSTAFF
    GERMAN_SHEPERD
    TERRIER
    DOBERMAN
    CANE_CORSO
    ROTTWEILER
    DASCHUND
    PUG
    BICHON
    GOLDEN_RETRIEVER
    GREAT_DANE
    PITBULL
    MASTIFF
    SHIBA_INU
    DOGO_ARGENTINO
    BULLDOG
    LABRADOR
    BEAGLE
    CHIHUAHUA
    POODLE
    COLLIE
    BOXER
    CHOW_CHOW
    ST_BERNARD
    POMERANIAN
    COCKEL
}

enum Food {
    CHICKEN
    BEEF
    TURKEY
    SALMON
    CHEESE
    APPLES
    BANANAS
    BLUEBERRIES
    STRAWBERRIES
    WATERMELON
    SWEETPOTATO
    YOGURT
    PEANUTBUTTER
}

type Query {
    # Obiect filtrat dupa argument
    dogById(id: ID!): Dog
    ownerById(id: ID!): Owner

    # Lista de obiecte
    allDogs: [Dog!]!
    allOwners: [Owner!]!

    # Lista de obiecte ce contin alte obiecte
    dogsWithOwners: [Dog!]!
    ownersWithDogs: [Owner!]!

    # Lista filtrata
    dogsByBreed(breed: DogBreed!): [Dog!]!
    dogsByColor(color: String!): [Dog!]!

    # Lista paginata
    dogsPaginated(page: Int!, size: Int!): DogPage!
    ownersPaginated(page: Int!, size: Int!): OwnerPage!
}

type Mutation {
    login(username: String!, password: String!): Boolean!
    addDog(input: DogInput!): Dog!
    addOwner(input: OwnerInput!): Owner!
    updateDog(id: ID!, input: DogInput!): Dog!
    updateOwner(id: ID!, input: OwnerInput!): Owner!
    deleteDog(id: ID!): Boolean!
    deleteOwner(id: ID!): Boolean!
}



