spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=asdasd123
spring.jpa.hibernate.ddl-auto=update
# client graphql pt testat:
spring.graphql.http.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# CORS
spring.graphql.cors.allowed-origins=http://localhost:3000
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allow-credentials=true